### ISSUE TITLE
[BUG]: does not seem to work?

### ISSUE THREAD

**Issue by TheChemicalWorkshop** [aaryanrr/DownDetector-CLI#4]
**Describe the bug**
just getting a flat error:
`Traceback (most recent call last):
  File "H:\Downloads\DownDetector-CLI-main\src\Scraper.py", line 29, in get_status
    text = status.find('div', attrs={'class': 'h2 entry-title'})
AttributeError: 'NoneType' object has no attribute 'find'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\Main.py", line 25, in <module>
    instance.get_status()
  File "H:\Downloads\DownDetector-CLI-main\src\Scraper.py", line 35, in get_status
    raise Errors.InvalidServiceName("Name of the Service is Invalid!")
src.Errors.InvalidServiceName: Name of the Service is Invalid!`

**To Reproduce**
`py .\Main.py` on windows 10
enter `gmail` or `rainbow-six`
press 1

**Expected behavior**
To work?

**Details (please complete the following information):**
 - OS: windows 10
 - Python: Python 3.7.2
 - Pip: no virtual env, requirements installed

**Additional context**
I'd like this working, as i dont want to re-write this
can you guys help?

**Comment by TheChemicalWorkshop** [comment]
did some digging, line 27 added print of soup

downdetector.com needs to review the security of your connection before proceeding.

guess cloudflare blocking?
